POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "username": "patient@example.com",
  "password": "demo123",
  "role": "patient"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "patient123"
}
###

GET http://localhost:5000/medications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InBhdGllbnQiLCJpYXQiOjE3NTAzOTkwMzUsImV4cCI6MTc1MDQ4NTQzNX0.VtZb5-aztj_1GLwyI5HAWLmtqVbxwZYLb4rLS_tc9j8
